name: Sync Repositories

on:
    push:
        branches:
            - master

jobs:
    sync:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout monorepo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup git user
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "naylour[bot]@ya.ru"

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan github.com >> ~/.ssh/known_hosts

            # === Grammar ===
            - name: Push grammar subtree
              run: |
                  git subtree push --prefix=grammar git@github.com:ParsecLab/pmlang-grammar.git master || echo "No changes in admin"
